version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
  php:
    image: php:8.1-apache
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql
